### PR TITLE
Update CocoaPods to 1.0

### PR DESCRIPTION
**Pull request by mdiiorio**

### CODE REVIEW

**Comment by dnkoutso** [comment]
LGTM.

**Comment by justinseanmartin** [comment]
Unfortunately, I don't think '~> 1.0' will match pre-release versions. Can you try and double check? I think it needs to be explicitly '1.0.0.beta.3'. You could release the plugin as a pre-release as well (e.g. 0.1.1.beta.1).

**Comment by mdiiorio** [comment]
You're right. Using the explicit beta version installs correctly.

**Comment by justinseanmartin** [comment]
LGTM

**Pull request merged**
